### ISSUE TITLE
v1.13 go mod incompatible

### ISSUE THREAD

**Issue by alexbeltran** [petergtz/pegomock#91]
When running:
```
go mod tidy
```

The following is outputted from the generated mock package.

```
go: finding github.com/petergtz/pegomock/matchers latest
github.com/...../mock/mCommand imports
        github.com/petergtz/pegomock tested by
        github.com/petergtz/pegomock.test imports
        github.com/petergtz/pegomock/matchers: module github.com/petergtz/pegomock@latest (v2.5.0+incompatible) found, but does not contain package github.com/petergtz/pegomock/matchers
```

Not clear why it is looking for a matchers library since it isn't in the generated mock package. See imports:

```
package mCommand

import (
	pegomock "github.com/petergtz/pegomock"
	command "....command"
	"reflect"
	"time"
)
```

**Comment by alexbeltran** [comment]
I was able to fix it by updating the go mod with:

require     github.com/petergtz/pegomock/matchers v0.0.0-00010101000000-000000000000 // indirect
replace github.com/petergtz/pegomock/matchers => github.com/petergtz/pegomock v2.5.0+incompatible

This is more of a hack to fix it though.

**Comment by petergtz** [comment]
Hi @alexbeltran,

thank you very much for reporting this. I don't have time to look into this right now, but will see if I can address it in the coming days. If you could provide me with some example file/directory structure, that  would help to speed things up quite a bit.

Thank you,
Peter

**Comment by petergtz** [comment]
@alexbeltran OK, finally had the time to look into this. So here's the issue:

`go mod tidy` adds your dependencies' test dependencies to your module. (See https://github.com/golang/go/issues/29323, https://github.com/golang/go/issues/27633, https://github.com/golang/go/issues/26626 and https://github.com/golang/go/issues/26955)

This causes an issue here, because [pegomock's own tests depend on a package](https://github.com/petergtz/pegomock/blob/master/dsl_test.go#L27) (i.e. the `matchers` package) which itself gets generated as part of the test suite.

I'm not sure I'm excited about the fact `go mod tidy` adds _test_ dependencies, because I don't see the use case of running your dependencies' test suites. Any integration test suite requires a certain environment to run anyway, so it's unrealistic to run them.

**I guess we could do the following:** commit the `matchers` package to git and therefore satisfy `go mod tidy`. They get temporarily removed by `scripts/run_tests.sh` anyway to make sure they get generated properly before the tests run.

Do you think that would solve your problem?

**Comment by petergtz** [comment]
@alexbeltran I just went ahead an made the change on `develop`. Could you try and see if that solves your problem?

**Comment by alexbeltran** [comment]
Thanks for investigating this so qiuckly. Sorry I didn't get back to you immediately.

The `develop` branch works for me which is great. :) I also agree, it is strange that go mod tidy would add test dependencies. >.> Including them does fix tidy though.

**Comment by petergtz** [comment]
Okay cool. Will make a release later this week.
